# Ansible Inventory - Auto-generated by Terraform
# Generated on: ${timestamp()}
# Using existing bastion host

[bastion]
bastion ansible_host=localhost ansible_connection=local ansible_user=ec2-user

[master]
master ansible_host=${master_private_ip} ansible_user=ec2-user

[workers]
%{ for idx, ip in worker_private_ips ~}
worker${idx + 1} ansible_host=${ip} ansible_user=ec2-user
%{ endfor ~}

[spark_master:children]
master

[spark_workers:children]
workers

[kafka:children]
master

[zookeeper:children]
master

[private_nodes:children]
master
workers

# Since we're running from bastion, no ProxyCommand needed
